import { GUIConfig } from '../gui-config';
declare const guiMiddleware: import("redux").StoreEnhancer<{
    dispatch: unknown;
}, {}>;
declare const buildInitialState: (config: GUIConfig) => {
    alerts: any;
    assetDrag: any;
    blockDrag: any;
    colorPicker: any;
    config: GUIConfig;
    connectionModal: any;
    customProcedures: any;
    editorTab: any;
    mode: any;
    hoveredTarget: any;
    stageSize: any;
    menus: any;
    micIndicator: any;
    modals: any;
    monitors: any;
    monitorLayout: any;
    platform: any;
    projectChanged: any;
    projectState: any;
    projectTitle: any;
    fontsLoaded: any;
    restoreDeletion: any;
    targets: any;
    settings: any;
    timeout: any;
    timeTravel: any;
    toolbox: any;
    vm: any;
    vmStatus: any;
    workspaceMetrics: any;
    blockDisplay: any;
    extensionFilter: any;
    meshV2: any;
    googleDriveFile: any;
    koshienFile: any;
    rubyCode: any;
    test: {
        isTest: boolean;
    };
};
declare const initPlayer: (currentState: any) => any;
declare const initFullScreen: (currentState: any) => any;
declare const initEmbedded: (currentState: any) => any;
declare const initTelemetryModal: (currentState: any) => any;
declare const guiReducer: import("redux").Reducer<import("redux").CombinedState<{
    alerts: any;
    assetDrag: any;
    blockDrag: any;
    colorPicker: any;
    connectionModal: any;
    config: GUIConfig | null;
    customProcedures: any;
    editorTab: any;
    mode: any;
    hoveredTarget: any;
    stageSize: any;
    menus: any;
    micIndicator: any;
    modals: any;
    monitors: any;
    monitorLayout: any;
    platform: any;
    projectChanged: any;
    projectState: any;
    projectTitle: any;
    fontsLoaded: any;
    restoreDeletion: any;
    targets: any;
    settings: any;
    timeout: any;
    timeTravel: any;
    toolbox: any;
    vm: any;
    vmStatus: any;
    workspaceMetrics: any;
    blockDisplay: any;
    extensionFilter: any;
    meshV2: any;
    googleDriveFile: any;
    koshienFile: any;
    rubyCode: any;
    test: any;
}>, any>;
export { guiReducer as default, buildInitialState, guiMiddleware, initEmbedded, initFullScreen, initPlayer, initTelemetryModal };
