import { localesInitialState, initLocale, selectLocale } from './reducers/locales.js';
import { buildInitialState, guiMiddleware, initEmbedded, initFullScreen, initPlayer } from './reducers/gui';
import { setFullScreen, setPlayer, setEmbedded } from './reducers/mode.js';
import { LoadingStates, onFetchedProjectData, onLoadedProject, defaultProjectId, manualUpdateProject, remixProject, requestNewProject, requestProjectUpload, setProjectId } from './reducers/project-state.js';
import { openBackdropLibrary, openCostumeLibrary, openDebugModal, openExtensionLibrary, openLoadingProject, openTelemetryModal, openSoundLibrary, openSpriteLibrary, openSoundRecorder, openConnectionModal, openTipsLibrary, closeBackdropLibrary, closeCostumeLibrary, closeDebugModal, closeExtensionLibrary, closeLoadingProject, closeTelemetryModal, closeSpriteLibrary, closeSoundLibrary, closeSoundRecorder, closeTipsLibrary, closeConnectionModal } from './reducers/modals.js';
import { setStageSize } from './reducers/stage-size';
import { activateDeck } from './reducers/cards';
import { markTutorialSeen } from './reducers/tutorial-onboarding';
export declare const guiReducers: {
    locales: any;
    scratchGui: import("redux").Reducer<import("redux").CombinedState<{
        test: any;
        classroom: any;
        classroomTutorial: any;
        dnclMode: any;
        meshV2: any;
        googleDriveFile: any;
        koshienFile: any;
        rubyCode: any;
        smalrubotFirmware: any;
        cards: any;
        tutorialOnboarding: any;
        paletteVisibility: any;
        alerts: any;
        assetDrag: any;
        blockDrag: any;
        colorPicker: any;
        connectionModal: any;
        config: import("./gui-config.js").GUIConfig | null;
        dynamicAssets: any;
        customProcedures: any;
        editorTab: any;
        mode: any;
        hoveredTarget: any;
        stageSize: any;
        menus: any;
        micIndicator: any;
        modals: any;
        monitors: any;
        monitorLayout: any;
        platform: any;
        projectChanged: any;
        projectState: any;
        projectTitle: any;
        fontsLoaded: any;
        restoreDeletion: any;
        targets: any;
        settings: any;
        timeout: any;
        timeTravel: any;
        toolbox: any;
        vm: any;
        vmStatus: any;
        workspaceMetrics: any;
        blockDisplay: any;
        extensionFilter: any;
    }>, any>;
    scratchPaint: any;
};
export { LoadingStates, onFetchedProjectData, onLoadedProject, defaultProjectId, manualUpdateProject, remixProject, requestNewProject, requestProjectUpload, setProjectId, setStageSize, activateDeck, markTutorialSeen, openBackdropLibrary, openCostumeLibrary, openDebugModal, openExtensionLibrary, openLoadingProject, openTelemetryModal, openSoundLibrary, openSpriteLibrary, openSoundRecorder, openConnectionModal, openTipsLibrary, closeBackdropLibrary, closeCostumeLibrary, closeDebugModal, closeExtensionLibrary, closeLoadingProject, closeTelemetryModal, closeSpriteLibrary, closeSoundLibrary, closeSoundRecorder, closeTipsLibrary, closeConnectionModal, buildInitialState, guiMiddleware, initEmbedded, initPlayer, initFullScreen, initLocale, localesInitialState, setFullScreen, setPlayer, setEmbedded, selectLocale };
