import './lib/log-suppression';
import { legacyConfig } from './legacy-config';
export { default } from './containers/gui.jsx';
export { default as GUIComponent } from './components/gui/gui.jsx';
export { default as AppStateHOC } from './lib/app-state-hoc.jsx';
export { setAppElement } from 'react-modal';
export { legacyConfig };
export declare const guiInitialState: {
    test: {
        isTest: boolean;
    };
    bugReport: any;
    classroom: any;
    classroomTutorial: any;
    dnclMode: any;
    meshV2: any;
    googleDriveFile: any;
    koshienFile: any;
    rubyCode: any;
    smalrubotFirmware: any;
    cards: any;
    tutorialOnboarding: any;
    paletteVisibility: any;
    alerts: any;
    assetDrag: any;
    blockDrag: any;
    colorPicker: any;
    config: import("./gui-config").GUIConfig;
    connectionModal: any;
    customProcedures: any;
    dynamicAssets: any;
    editorTab: any;
    mode: any;
    hoveredTarget: any;
    stageSize: any;
    menus: any;
    micIndicator: any;
    modals: any;
    monitors: any;
    monitorLayout: any;
    platform: any;
    projectChanged: any;
    projectState: any;
    projectTitle: any;
    fontsLoaded: any;
    restoreDeletion: any;
    targets: any;
    settings: any;
    timeout: any;
    timeTravel: any;
    toolbox: any;
    vm: any;
    vmStatus: any;
    workspaceMetrics: any;
    blockDisplay: any;
    extensionFilter: any;
};
export * from './exported-reducers';
